// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Akim Zuev",
            "email": "akim.zuev.86@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "description": "Проверяет email и пароль. При успехе создаёт сессию и устанавливает HttpOnly-cookie ` + "`" + `rx_session` + "`" + `.\nАккаунт должен быть активирован (email подтверждён через письмо).\nПосле 5 неудачных попыток аккаунт блокируется на 15 минут.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход",
                "parameters": [
                    {
                        "description": "Учётные данные",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный вход, cookie rx_session выставлен",
                        "schema": {
                            "$ref": "#/definitions/transport.loginResponse"
                        }
                    },
                    "401": {
                        "description": "Неверные учётные данные или аккаунт не активирован (код: invalid_credentials)",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Аккаунт заблокирован (код: user_blocked)",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Завершает текущую сессию, инвалидирует cookie ` + "`" + `rx_session` + "`" + `.\nТребует валидной сессии и совпадения заголовка Origin (CSRF-защита).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выход",
                "responses": {
                    "204": {
                        "description": "Сессия завершена"
                    },
                    "401": {
                        "description": "Сессия не найдена или истекла",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "403": {
                        "description": "CSRF — Origin не совпадает с разрешёнными",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/me": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Возвращает данные аутентифицированного пользователя: id, email, displayName, статус, дату регистрации.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Профиль текущего пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/transport.meResponse"
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или истекла",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Изменяет отображаемое имя (displayName) текущего пользователя.\nТребует валидной сессии и совпадения Origin (CSRF-защита).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Обновить профиль",
                "parameters": [
                    {
                        "description": "Новое отображаемое имя",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.updateMeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Обновлённые данные пользователя",
                        "schema": {
                            "$ref": "#/definitions/transport.loginResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Не аутентифицирован",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "403": {
                        "description": "CSRF — Origin не совпадает",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/password/forgot": {
            "post": {
                "description": "Выдаёт одноразовый токен сброса пароля и отправляет письмо, если email принадлежит активному аккаунту.\nВсегда возвращает 202 — сервер не раскрывает, существует ли аккаунт с таким email.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Запрос сброса пароля",
                "parameters": [
                    {
                        "description": "Email пользователя",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.forgotPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Письмо отправлено или запрос принят"
                    }
                }
            }
        },
        "/api/auth/password/reset": {
            "post": {
                "description": "Принимает одноразовый токен и новый пароль. При успехе отзывает все сессии пользователя.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Сброс пароля",
                "parameters": [
                    {
                        "description": "Токен и новый пароль",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.resetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Пароль изменён, сессии отозваны"
                    },
                    "400": {
                        "description": "Неверный запрос, слабый пароль или недействительный токен",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/register": {
            "post": {
                "description": "Создаёт нового пользователя. На указанный email отправляется письмо для подтверждения.\nВойти можно только после перехода по ссылке из письма (активация аккаунта).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация",
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Пользователь создан, письмо отправлено",
                        "schema": {
                            "$ref": "#/definitions/transport.registerResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса, некорректный email или слабый пароль (код: bad_request / invalid_email / weak_password)",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Email уже зарегистрирован (код: email_taken)",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/verification/resend": {
            "post": {
                "description": "Отправляет новое письмо с токеном верификации.\nВсегда возвращает 202 — сервер не раскрывает, существует ли аккаунт с таким email (защита от перебора).",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Повторная отправка письма",
                "parameters": [
                    {
                        "description": "Email пользователя",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.resendRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Письмо отправлено (или будет отправлено, если email зарегистрирован)"
                    }
                }
            }
        },
        "/api/auth/verify": {
            "get": {
                "description": "Принимает одноразовый токен из письма, активирует аккаунт и перенаправляет на фронтенд.\nПри успехе — редирект на ` + "`" + `/login?verified=1` + "`" + `, при ошибке или истёкшем токене — на ` + "`" + `/login?verified=0` + "`" + `.",
                "tags": [
                    "auth"
                ],
                "summary": "Подтверждение email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Одноразовый токен из письма (plaintext)",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Редирект на фронтенд с verified=0 (токен не найден, уже использован или истёк)"
                    }
                }
            }
        },
        "/api/competitors/{competitorId}": {
            "delete": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Удаляет competitor link и историю цен. Доступ ограничен владельцем товара.",
                "tags": [
                    "competitors"
                ],
                "summary": "Удалить конкурента",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID конкурента",
                        "name": "competitorId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Конкурент удалён"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Сбрасывает последнюю цену и статус проверки, затем сохраняет новый Ozon URL/public product ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "competitors"
                ],
                "summary": "Обновить ссылку конкурента",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID конкурента",
                        "name": "competitorId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "target: Ozon URL или public product ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.competitorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Обновлённый конкурент",
                        "schema": {
                            "$ref": "#/definitions/transport.competitorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/competitors/{competitorId}/refresh": {
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Проверяет публичную страницу Ozon через изолированный adapter, сохраняет safe status/error code и snapshot. Raw parser/external errors не возвращаются.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "competitors"
                ],
                "summary": "Обновить цену конкурента",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID конкурента",
                        "name": "competitorId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Цена обновлена",
                        "schema": {
                            "$ref": "#/definitions/transport.competitorResponse"
                        }
                    },
                    "202": {
                        "description": "Проверка выполнена с безопасным кодом ошибки",
                        "schema": {
                            "$ref": "#/definitions/transport.competitorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/imports/{id}": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Возвращает user-scoped статус импорта, counters и capped список ошибок.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Статус импорта SKU",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID импорта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Статус импорта",
                        "schema": {
                            "$ref": "#/definitions/transport.importStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Отменяет импорт со статусом pending или running. Если импорт уже завершён — возвращает 409.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Отменить импорт",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID импорта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Импорт отменён"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Импорт уже завершён или не найден",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/imports/{id}/errors": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Возвращает постраничный список ошибок конкретного импорта (только для импортов пользователя).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Детали ошибок импорта",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID импорта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Номер страницы (с 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Размер страницы (1–100, по умолчанию 20)",
                        "name": "perPage",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список ошибок с пагинацией",
                        "schema": {
                            "$ref": "#/definitions/transport.importErrorsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Импорт не найден",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/products": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Возвращает постраничный список товаров пользователя с фильтрацией и сортировкой.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Список товаров",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Полнотекстовый поиск по названию и SKU",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Фильтр по UUID магазина",
                        "name": "shopId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Фильтр по статусу: active | archived | out_of_stock",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Фильтр по наличию стратегии",
                        "name": "hasStrategy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Поле сортировки: name | current_price | updated_at (по умолчанию)",
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Направление: asc | desc (по умолчанию)",
                        "name": "sortDir",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Фильтр: цена не ниже",
                        "name": "priceFrom",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Фильтр: цена не выше",
                        "name": "priceTo",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Номер страницы (с 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Размер страницы (1–100, по умолчанию 50)",
                        "name": "perPage",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список товаров с пагинацией",
                        "schema": {
                            "$ref": "#/definitions/transport.productListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/products/bulk-patch": {
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Обновляет min_price/max_price/cost_price для набора товаров (до 100) за один запрос.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Массовое обновление цен",
                "parameters": [
                    {
                        "description": "Список товаров с изменениями",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.bulkPatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Количество обновлённых товаров",
                        "schema": {
                            "$ref": "#/definitions/transport.bulkPatchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/products/export": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Возвращает все товары пользователя (с учётом фильтров) в виде CSV-файла. Лимит 10 000 строк.",
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Экспорт каталога в CSV",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Фильтр по UUID магазина",
                        "name": "shopId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Фильтр по статусу: active | archived | out_of_stock",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Полнотекстовый поиск",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Поле сортировки",
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Направление: asc | desc",
                        "name": "sortDir",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Цена не ниже",
                        "name": "priceFrom",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Цена не выше",
                        "name": "priceTo",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "CSV-файл с товарами",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/products/{id}": {
            "delete": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Переводит товар в статус archived. Данные не удаляются.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Архивировать товар (soft-delete)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID товара",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Товар архивирован"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Товар не найден",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Устанавливает min_price, max_price и/или cost_price. Передавайте только изменяемые поля; null сбрасывает значение.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Обновить цены товара",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID товара",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Поля: minPrice, maxPrice, costPrice (number | null)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Обновлённый товар",
                        "schema": {
                            "$ref": "#/definitions/transport.productResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Товар не найден",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/products/{id}/competitors": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Возвращает привязанные к товару Ozon competitor URL/public product ID. Доступ только к товарам текущего пользователя.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "competitors"
                ],
                "summary": "Список конкурентов товара",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID товара",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Конкуренты товара",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/transport.competitorResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Принимает ссылку на товар Ozon или публичный ID товара Ozon. Цена обновляется отдельным refresh-запросом.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "competitors"
                ],
                "summary": "Добавить конкурента к товару",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID товара",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "target: Ozon URL или public product ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.competitorRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Созданный конкурент",
                        "schema": {
                            "$ref": "#/definitions/transport.competitorResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный target",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Товар не найден",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Дубликат конкурента",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/shops": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Возвращает все магазины, принадлежащие аутентифицированному пользователю.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shops"
                ],
                "summary": "Список магазинов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/transport.shopResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Сессия отсутствует или истекла",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Создаёт новый магазин, сохраняет API-ключи в зашифрованном виде (AES-GCM).\n\nФормат поля ` + "`" + `credentials` + "`" + ` зависит от маркетплейса:\n- **wb** (Wildberries): ` + "`" + `{\"api_key\": \"\u003cAPI-токен\u003e\"}` + "`" + `\nТокен можно получить в личном кабинете WB: Настройки → Доступ к API.\n- **ozon**: ` + "`" + `{\"client_id\": \"\u003cClient-ID\u003e\", \"api_key\": \"\u003cAPI-ключ\u003e\"}` + "`" + `\nКлючи доступны в кабинете Ozon Seller: Настройки → API-ключи.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shops"
                ],
                "summary": "Подключить магазин",
                "parameters": [
                    {
                        "description": "Данные нового магазина",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.createShopRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Магазин создан",
                        "schema": {
                            "$ref": "#/definitions/transport.shopResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат или неизвестный маркетплейс (код: bad_request / invalid_marketplace)",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Не аутентифицирован",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "403": {
                        "description": "CSRF — Origin не совпадает",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/shops/{id}": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Возвращает магазин по UUID. Доступен только владельцу.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shops"
                ],
                "summary": "Получить магазин",
                "parameters": [
                    {
                        "type": "string",
                        "example": "550e8400-e29b-41d4-a716-446655440000",
                        "description": "UUID магазина",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/transport.shopResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат UUID",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Не аутентифицирован",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Магазин не найден (код: shop_not_found)",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Удаляет магазин и все связанные данные.\nЕсли за последние 30 дней есть записи в журнале изменений цен — операция будет отклонена.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shops"
                ],
                "summary": "Удалить магазин",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID магазина",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Магазин удалён"
                    },
                    "400": {
                        "description": "Неверный формат UUID",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Не аутентифицирован",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "403": {
                        "description": "CSRF — Origin не совпадает",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Магазин не найден",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Изменяет имя, учётные данные и/или настройки автообновления и расписания.\nВсе поля опциональны — передавайте только то, что хотите изменить.\n\nПоле ` + "`" + `scheduleCron` + "`" + ` задаёт расписание пересчёта цен в формате cron (5 полей).\nПримеры: ` + "`" + `\"0 * * * *\"` + "`" + ` — каждый час, ` + "`" + `\"0 */4 * * *\"` + "`" + ` — каждые 4 часа.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shops"
                ],
                "summary": "Обновить магазин",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID магазина",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Обновляемые поля",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.updateShopRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/transport.shopResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Не аутентифицирован",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "403": {
                        "description": "CSRF или нет доступа к магазину",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Магазин не найден",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/shops/{id}/products": {
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Создаёт товар в указанном магазине без обращения к API маркетплейса.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Добавить товар вручную",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID магазина",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные товара",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.createProductRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Созданный товар",
                        "schema": {
                            "$ref": "#/definitions/transport.productResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Магазин не найден",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "409": {
                        "description": "SKU уже существует в этом магазине",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/shops/{id}/products/import": {
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Создаёт durable background job импорта товаров магазина и возвращает ID импорта для polling.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Запустить импорт SKU",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID магазина",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Импорт поставлен в очередь",
                        "schema": {
                            "$ref": "#/definitions/transport.importStartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Импорт уже выполняется",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "429": {
                        "description": "Cooldown импорта",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/shops/{id}/test": {
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Выполняет тестовый запрос к API маркетплейса с сохранёнными учётными данными.\nПри успехе статус магазина становится ` + "`" + `active` + "`" + `, при ошибке авторизации — ` + "`" + `error` + "`" + `.\nРезультат проверки фиксируется в поле ` + "`" + `lastCheckedAt` + "`" + `.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shops"
                ],
                "summary": "Проверить подключение к маркетплейсу",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID магазина",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Подключение успешно",
                        "schema": {
                            "$ref": "#/definitions/transport.testConnectionResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат UUID",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Не аутентифицирован",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "403": {
                        "description": "CSRF — Origin не совпадает",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Магазин не найден",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "422": {
                        "description": "Ошибка авторизации в маркетплейсе (код: auth_failed)",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/transport.errorResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Возвращает 200, если процесс запущен. Не проверяет зависимости.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Возвращает 200, если Postgres и Redis доступны.\nПри недоступности любого из них — 503 с описанием причины.\nИспользуется как healthcheck в Docker Compose и CI.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "503": {
                        "description": "db unavailable / redis unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "transport.bulkPatchProductItem": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "costPrice": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "maxPrice": {
                    "type": "number"
                },
                "minPrice": {
                    "type": "number"
                }
            }
        },
        "transport.bulkPatchRequest": {
            "type": "object",
            "required": [
                "products"
            ],
            "properties": {
                "products": {
                    "type": "array",
                    "maxItems": 100,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/transport.bulkPatchProductItem"
                    }
                }
            }
        },
        "transport.bulkPatchResponse": {
            "type": "object",
            "properties": {
                "updated": {
                    "type": "integer"
                }
            }
        },
        "transport.competitorRequest": {
            "type": "object",
            "required": [
                "target"
            ],
            "properties": {
                "target": {
                    "type": "string"
                }
            }
        },
        "transport.competitorResponse": {
            "type": "object",
            "properties": {
                "competitorUrl": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastAvailability": {
                    "type": "string"
                },
                "lastCheckedAt": {
                    "type": "string"
                },
                "lastErrorCode": {
                    "type": "string"
                },
                "lastPrice": {
                    "type": "number"
                },
                "lastStatus": {
                    "type": "string"
                },
                "marketplace": {
                    "type": "string"
                },
                "ozonPublicProductId": {
                    "type": "string"
                },
                "productId": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "transport.createProductRequest": {
            "type": "object",
            "required": [
                "externalSku",
                "name"
            ],
            "properties": {
                "costPrice": {
                    "type": "number"
                },
                "currency": {
                    "type": "string"
                },
                "currentPrice": {
                    "type": "number"
                },
                "externalSku": {
                    "type": "string"
                },
                "maxPrice": {
                    "type": "number"
                },
                "minPrice": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "transport.createShopRequest": {
            "type": "object"
        },
        "transport.errorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "invalid_credentials"
                },
                "message": {
                    "type": "string",
                    "example": "Неверный email или пароль"
                }
            }
        },
        "transport.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/transport.errorDetail"
                }
            }
        },
        "transport.forgotPasswordRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                }
            }
        },
        "transport.importErrorDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "externalSku": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "transport.importErrorsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/transport.importErrorDTO"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "perPage": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "transport.importStartResponse": {
            "type": "object",
            "properties": {
                "importId": {
                    "type": "string"
                },
                "jobId": {
                    "type": "string"
                },
                "pollUrl": {
                    "type": "string"
                },
                "shopId": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "transport.importStatusResponse": {
            "type": "object",
            "properties": {
                "added": {
                    "type": "integer"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/transport.importErrorDTO"
                    }
                },
                "failed": {
                    "type": "integer"
                },
                "finishedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "jobId": {
                    "type": "string"
                },
                "jobStatus": {
                    "type": "string"
                },
                "shopId": {
                    "type": "string"
                },
                "skipped": {
                    "type": "integer"
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                },
                "updated": {
                    "type": "integer"
                }
            }
        },
        "transport.loginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "MyP@ssword123"
                }
            }
        },
        "transport.loginResponse": {
            "type": "object",
            "properties": {
                "displayName": {
                    "type": "string",
                    "example": "Иван Петров"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "transport.meResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string",
                    "example": "Иван Петров"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "status": {
                    "type": "string",
                    "example": "active"
                }
            }
        },
        "transport.paginationInfo": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "perPage": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "transport.productListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/transport.productResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/transport.paginationInfo"
                }
            }
        },
        "transport.productResponse": {
            "type": "object",
            "properties": {
                "costPrice": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "currentPrice": {
                    "type": "number"
                },
                "externalSku": {
                    "type": "string"
                },
                "hasStrategy": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "lastSyncedAt": {
                    "type": "string"
                },
                "maxPrice": {
                    "type": "number"
                },
                "minPrice": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "rating": {
                    "type": "number"
                },
                "reviewsCount": {
                    "type": "integer"
                },
                "shopId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "stockCount": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "transport.registerRequest": {
            "type": "object",
            "required": [
                "displayName",
                "email",
                "password"
            ],
            "properties": {
                "displayName": {
                    "type": "string",
                    "example": "Иван Петров"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "MyP@ssword123"
                }
            }
        },
        "transport.registerResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                }
            }
        },
        "transport.resendRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                }
            }
        },
        "transport.resetPasswordRequest": {
            "type": "object",
            "required": [
                "token"
            ],
            "properties": {
                "newPassword": {
                    "type": "string",
                    "example": "NewValidPass123!"
                },
                "password": {
                    "type": "string",
                    "example": "NewValidPass123!"
                },
                "passwordConfirmation": {
                    "type": "string",
                    "example": "NewValidPass123!"
                },
                "token": {
                    "type": "string",
                    "example": "q83s..."
                }
            }
        },
        "transport.shopResponse": {
            "type": "object",
            "properties": {
                "autoUpdateEnabled": {
                    "type": "boolean",
                    "example": false
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "lastCheckedAt": {
                    "type": "string"
                },
                "marketplace": {
                    "type": "string",
                    "example": "wb"
                },
                "name": {
                    "type": "string",
                    "example": "Мой магазин на WB"
                },
                "scheduleCron": {
                    "type": "string",
                    "example": "0 */4 * * *"
                },
                "status": {
                    "type": "string",
                    "example": "active"
                }
            }
        },
        "transport.testConnectionResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "active"
                }
            }
        },
        "transport.updateMeRequest": {
            "type": "object",
            "required": [
                "displayName"
            ],
            "properties": {
                "displayName": {
                    "type": "string",
                    "example": "Новое Имя"
                }
            }
        },
        "transport.updateShopRequest": {
            "type": "object",
            "properties": {
                "autoUpdateEnabled": {
                    "type": "boolean",
                    "example": true
                },
                "credentials": {
                    "type": "object"
                },
                "name": {
                    "type": "string",
                    "example": "Новое название"
                },
                "scheduleCron": {
                    "type": "string",
                    "example": "0 */4 * * *"
                }
            }
        }
    },
    "securityDefinitions": {
        "SessionCookie": {
            "description": "Сессионный cookie, выставляемый при логине (POST /api/auth/login).",
            "type": "apiKey",
            "name": "rx_session",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "RepricerX API",
	Description:      "REST API сервиса автоматического управления ценами на маркетплейсах Wildberries и Ozon.\n\n## Аутентификация\nПосле успешного входа (POST /api/auth/login) сервер устанавливает HttpOnly-cookie `rx_session`.\nБраузер отправляет его автоматически; при работе через curl/Postman передавайте `-b \"rx_session=<token>\"`.\n\n## CSRF-защита\nВсе мутирующие эндпоинты (POST/PATCH/DELETE), кроме `/api/auth/register`, `/api/auth/login`,\n`/api/auth/verification/resend`, `/api/auth/password/forgot` и `/api/auth/password/reset`, проверяют заголовок `Origin`.\nОн должен совпадать с одним из разрешённых источников (настраивается через `ALLOWED_ORIGINS`).\nSwagger UI выставляет `Origin` автоматически.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
